### PR TITLE
Update gsoc.yml

### PR DESCRIPTION
**Pull request by nikita-astronaut**

### CODE REVIEW

**Comment by dpshelio** [comment]
We normally prefer the blog to be from the student page, so people may find interesting other things they may blog about.
Also if we are going to use poliastro's blog, then I need feed for only GSoC related posts.

**Comment by astrojuanlu** [comment]
Sorry, my fault - I gave the wrong instructions to @nikita-astronaut. poliastro blog is not exclusively for GSOC.

**Comment by dpshelio** [comment]
Should then we close this?

**Comment by astrojuanlu** [comment]
Yes, let's close it.

**Pull request closed without merging**
